### ISSUE TITLE
Humanist style `g`

### ISSUE THREAD

**Issue by oshytiko** [N-R-K/JetBrainsNRK#1]
Hey 👋

Really like your font. Especially condensed version. It became more comfortable for me than usual Iosevka!

Was wondering, what do you think about more "old school `g`"? The one with loop. Like, for example, Consolas has? I find it more distinct in coding situation. Would you be open to adding it to your excellent edition?

Many thanks in advance!

**Comment by N-R-K** [comment]
> Really like your font. Especially condensed version. It became more comfortable for me than usual Iosevka!

Glad to hear that other's have found it useful.

> Was wondering, what do you think about more "old school g"? The one with loop. Like, for example, Consolas has? I find it more distinct in coding situation. Would you be open to adding it to your excellent edition?

Not a fan of it - and this repo is just *"here's what I use, just making it publicly available in case someone else finds it useful too"* - and not really meant to be a proper/maintained project.

But in case you're interested in pursuing it, I think it should be fairly trivial with [fontforge](https://fontforge.org/en-US/). IIRC the steps I used to replace the jetbrains `u` with the dejavu `u` was following:

* Open both fonts in fontforge gui
* Select the glyph you want and copy it with <kbd>ctrl+c</kbd>
* Select the glyph on the other window and paste/overwrite it with <kbd>ctrl+v</kbd>
* If necessary scale the font via `Element > Transform`
* "Generate font" to save the changes to a new file.

fontforge also offers a python interface, so if you're planning to replace more than one glyph you might want to automate it via scripting. Good luck.

**Comment by N-R-K** [comment]
I've been trying out the [alternate `g` variant](https://github.com/JetBrains/JetBrainsMono/blob/8c3ccf768d899b989a8843ae6bfaad3177c82303/images/character-variants%402x.png) that comes with JetBrains Mono for a couple days and ended up liking it. Version [`2.1.0`](https://github.com/N-R-K/NRK-Mono/releases/tag/v2.1.0) now uses it as the default.

**Comment by oshytiko** [comment]
Amazing!!!! Thank you!
