### ISSUE TITLE
Add .zip or any other format supported in MacOS OOB

### ISSUE THREAD

**Issue by oshytiko** [N-R-K/JetBrainsNRK#4]
Please help us, soy latte drinking hipsters with MacBooks!

I had to run

```
brew install zstd
tar --use-compress-program=unzstd -xvf NRK-Mono-v2.1.0.tar.zst
open NRK-Mono-v2.1.0
```

just to open fonts folder!

Maybe `.zip` or `tar.gz` could also be added as a backup option?

**Comment by N-R-K** [comment]
This is actually something I've been thinking about too. On one hand zip files are much more widely supported (works OOB on windows as well) on the other hand, when it comes to compression ratio, zstd is miles ahead. Here's a recent experiment (done on the victor mono font from [nerd-fonts](https://github.com/ryanoasis/nerd-fonts/releases/tag/v3.0.0)):

```console
[/tmp]~> du -h VictorMono.* | sort -nr
67M     VictorMono.zip
67M     VictorMono.tar.gz
65M     VictorMono.tar.bz2
4.7M    VictorMono.tar.zst
```

The `.zip` was the original file and the `tar.*` were made by me with highest compression setting applied for each format. The difference, as you can see, is staggering (NOTE to self: open an issue on nerd font repo asking them to provide ultra compressed `.tar.zst` as alternative).

However, unlike some of the nerd-fonts, NRK-Mono isn't *that* large (currently it's around 15MiB uncompressed). So maybe a shabbily compressed `zip` or `tar.gz` wouldn't be too bad, especially considering their wide availability OOB.

I'll think a bit more about it :)

**Comment by N-R-K** [comment]
I've updated the README with instructions on how to extract `.tar.zst` - decided not to provide `.zip` files. Some more details are in the commit message: c822280.
