### ISSUE TITLE
How about make a Texture Healing enabled version of Jetbrains Mono?

### ISSUE THREAD

**Issue by tianfanghan** [N-R-K/JetBrainsNRK#6]
This year the font Monaspace appears, and the Texture healing feature is awesome. The official Jetbrains will not follow it quickly, well, would you please do this for all Jetbrains mono fans?

**Comment by N-R-K** [comment]
> would you please do this

I'm not a font designer and have no clue how to do that.

> Texture healing works by finding each pair of adjacent characters where one wants more space, and one has too much. Narrow characters are swapped for ones that cede some of their whitespace, and wider characters are swapped for ones that extend to the very edge of their box
> 
> \- https://monaspace.githubnext.com

And besides, I don't think it's a good thing either. I like my font to stay static. I don't like it dynamically changing appearance (which is why ligatures are disabled in this repo).
